name: Deploy Chat App on Git push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
  
    runs-on: self-hosted
    
    steps:
      - name: File Permissions
        run: |
            sudo chown -R $USER:$USER .
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create secrets.properties
        env:
          PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
        run: |
            echo "$PROPERTIES" > backend/src/main/resources/secrets.properties
      - name: Shut Down Old Version
        run: |
            cd backend
            bash shutDownOldVersion.sh
            sleep 5
      - name: Copy files to desired directory and run Spring Boot
        env:
          TARGET: ${{ secrets.TARGET_FOLDER }}
        run: |
            sudo find "$TARGET" &> /dev/null && sudo rm -r "$TARGET"
            sudo mkdir "$TARGET"
            sudo mv -v ./* "$TARGET" &> /dev/null
            cd "$TARGET"
            cd backend
            sudo nohup mvn spring-boot:run -Dspring-boot.run.jvmArguments="-XX:MaxRAM=250m -XX:+UseSerialGC -XX:InitiatingHeapOccupancyPercent=30" > spring-log.txt 2>&1 &